getwd()
setwd("~/Desktop/R/Coursera/exploratory")
data <- read.table('household_power_consumption.txt', header=TRUE, sep=";", stringsAsFactors=FALSE, na.strings="?")
dataneed <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
dataneeddatetime  <- paste(dataneed$Date,dataneed$Time,sep=" ")
datetime  <- strptime(dataneeddatetime, format="%d/%m/%Y  %H:%M:%S")
par()
par(mfrow = c(2, 2),mar=c(4,5,2,2))
plot(datetime,dataneed$Global_active_power,xlab="",ylab="Global Active Power",type="l")
plot(datetime,dataneed$Voltage,xlab="datetime",ylab="Voltage",type="l")
plot(datetime,dataneed$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering",col="black")
lines(datetime,dataneed$Sub_metering_2,col="red")
lines(datetime,dataneed$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=2, cex=0.5)
plot(datetime,dataneed$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type="l")
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()
