getwd()
setwd("~/Desktop/R/Coursera/exploratory")
data <- read.table('household_power_consumption.txt', header=TRUE, sep=";", stringsAsFactors=FALSE, na.strings="?")
dataneed <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
dataneeddatetime  <- paste(dataneed$Date,dataneed$Time,sep=" ")
datetime  <- strptime(dataneeddatetime, format="%d/%m/%Y  %H:%M:%S") 
plot(datetime,dataneed$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering",col="black")
lines(datetime,dataneed$Sub_metering_2,col="red")
lines(datetime,dataneed$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=2)
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()
